# Generated by Django 3.1.7 on 2021-04-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computing', 'Computing'), ('Gaming', 'Gaming'), ('Phones', 'Phones'), ('TV & Vidoe', 'TV & Video'), ('Photography', 'Photography'), ('Music & Sound', 'Music & Sound'), ('Home Applliances', 'Home Applliances'), ('Office Electronics', 'Office Electronics')], default='Computing', max_length=150),
        ),
    ]
