# Generated by Django 3.1.7 on 2021-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='second_name',
            field=models.CharField(default='vendor', max_length=100),
        ),
    ]
