# Generated by Django 3.1.7 on 2021-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210410_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='second_name',
            field=models.CharField(max_length=100),
        ),
    ]
