# Generated by Django 3.1.7 on 2021-04-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210414_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='city',
            new_name='estate',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='state',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='zipcode',
            new_name='town',
        ),
    ]
