# Generated by Django 3.1.7 on 2021-04-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210421_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, default='Tronic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.vendor'),
        ),
    ]
